"""initial schema

Revision ID: db761825af69
Revises:
Create Date: 2026-07-25 23:43:00.811151
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "db761825af69"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_items",
        sa.Column("item_id", sa.String(length=64), nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=True),
        sa.Column("listing_id", sa.String(length=128), nullable=True),
        sa.Column("asset_id", sa.String(length=128), nullable=True),
        sa.Column("skin_id", sa.String(length=256), nullable=False),
        sa.Column("market_hash_name", sa.String(length=512), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("contract_id", sa.String(length=32), nullable=True),
        sa.Column("acquisition_cost_minor", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("balance_type", sa.String(length=32), nullable=True),
        sa.Column("raw_float", sa.String(length=64), nullable=True),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trade_lock_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("history_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("item_id"),
    )
    with op.batch_alter_table("inventory_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inventory_items_contract_id"), ["contract_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_inventory_items_skin_id"), ["skin_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_inventory_items_state"), ["state"], unique=False)

    op.create_table(
        "ledger_events",
        sa.Column("event_id", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("balance_type", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("reference", sa.String(length=256), nullable=False),
        sa.Column("contract_id", sa.String(length=32), nullable=True),
        sa.Column("item_id", sa.String(length=64), nullable=True),
        sa.Column("venue", sa.String(length=64), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    with op.batch_alter_table("ledger_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ledger_events_contract_id"), ["contract_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ledger_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ledger_events_item_id"), ["item_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ledger_events_occurred_at"), ["occurred_at"], unique=False
        )

    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=False),
        sa.Column("listing_id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=False),
        sa.Column("skin_id", sa.String(length=256), nullable=False),
        sa.Column("market_hash_name", sa.String(length=512), nullable=False),
        sa.Column("collection_id", sa.String(length=256), nullable=False),
        sa.Column("rarity", sa.String(length=32), nullable=False),
        sa.Column("quality_type", sa.String(length=32), nullable=False),
        sa.Column("raw_float", sa.String(length=64), nullable=False),
        sa.Column("normalized_float", sa.String(length=64), nullable=False),
        sa.Column("price_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("balance_type", sa.String(length=32), nullable=False),
        sa.Column("buyer_fee_minor", sa.BigInteger(), nullable=False),
        sa.Column("deposit_fee_minor", sa.BigInteger(), nullable=False),
        sa.Column("paint_index", sa.Integer(), nullable=True),
        sa.Column("paint_seed", sa.Integer(), nullable=True),
        sa.Column("seller_reliability", sa.String(length=32), nullable=True),
        sa.Column("trade_lock_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tradable_status", sa.String(length=32), nullable=False),
        sa.Column("listing_status", sa.String(length=32), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_payload_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venue", "listing_id", name="uq_listing_identity"),
    )
    with op.batch_alter_table("listings", schema=None) as batch_op:
        batch_op.create_index(
            "ix_listing_collection_rarity", ["collection_id", "rarity"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_listings_asset_id"), ["asset_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_listings_collection_id"), ["collection_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_listings_skin_id"), ["skin_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_listings_venue"), ["venue"], unique=False)

    op.create_table(
        "metadata_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("revision", sa.String(length=128), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("skin_count", sa.Integer(), nullable=False),
        sa.Column("collection_count", sa.Integer(), nullable=False),
        sa.Column("issue_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "revision", "payload_sha256", name="uq_metadata_snapshot"),
    )
    op.create_table(
        "raw_payloads",
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("byte_length", sa.Integer(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint("payload_sha256"),
    )
    op.create_table(
        "realized_contract_results",
        sa.Column("contract_id", sa.String(length=32), nullable=False),
        sa.Column("rule_version", sa.String(length=128), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("predicted_ev_minor", sa.BigInteger(), nullable=False),
        sa.Column("predicted_roi", sa.String(length=64), nullable=False),
        sa.Column("predicted_sale_value_minor", sa.BigInteger(), nullable=False),
        sa.Column("predicted_capital_days", sa.String(length=32), nullable=False),
        sa.Column("predicted_distribution_json", sa.JSON(), nullable=False),
        sa.Column("actual_output_skin_id", sa.String(length=256), nullable=True),
        sa.Column("actual_output_float", sa.String(length=64), nullable=True),
        sa.Column("actual_gross_sale_minor", sa.BigInteger(), nullable=True),
        sa.Column("actual_fees_minor", sa.BigInteger(), nullable=True),
        sa.Column("actual_settled_proceeds_minor", sa.BigInteger(), nullable=True),
        sa.Column("actual_capital_days", sa.String(length=32), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("contract_id"),
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=False),
        sa.Column("listing_id", sa.String(length=128), nullable=False),
        sa.Column("candidate_id", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("reserved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reservations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reservations_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(
            "uq_active_reservation_per_listing",
            ["venue", "listing_id"],
            unique=True,
            sqlite_where=sa.text("is_active IS 1"),
            postgresql_where=sa.text("is_active IS 1"),
        )

    op.create_table(
        "scans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rule_version", sa.String(length=128), nullable=False),
        sa.Column("metadata_revision", sa.String(length=128), nullable=False),
        sa.Column("settings_json", sa.JSON(), nullable=False),
        sa.Column("statistics_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scans_scanned_at"), ["scanned_at"], unique=False)

    op.create_table(
        "candidates",
        sa.Column("candidate_id", sa.String(length=32), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=True),
        sa.Column("rule_version", sa.String(length=128), nullable=False),
        sa.Column("metadata_revision", sa.String(length=128), nullable=False),
        sa.Column("composition_signature", sa.String(length=512), nullable=False),
        sa.Column("input_rarity", sa.String(length=32), nullable=False),
        sa.Column("input_count", sa.Integer(), nullable=False),
        sa.Column("output_quality", sa.String(length=32), nullable=False),
        sa.Column("procurement_mode", sa.String(length=64), nullable=False),
        sa.Column("average_normalized_numerator", sa.BigInteger(), nullable=False),
        sa.Column("average_normalized_denominator", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_identities_json", sa.JSON(), nullable=False),
        sa.Column("outcomes_json", sa.JSON(), nullable=False),
        sa.Column("optimizer_explanation_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
        ),
        sa.PrimaryKeyConstraint("candidate_id"),
    )
    op.create_table(
        "candidate_evaluations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("candidate_id", sa.String(length=32), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rule_version", sa.String(length=128), nullable=False),
        sa.Column("fee_schedule_id", sa.String(length=128), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("input_cost_minor", sa.BigInteger(), nullable=False),
        sa.Column("buyer_fees_minor", sa.BigInteger(), nullable=False),
        sa.Column("deposit_fees_minor", sa.BigInteger(), nullable=False),
        sa.Column("fx_cost_minor", sa.BigInteger(), nullable=False),
        sa.Column("payment_surcharge_minor", sa.BigInteger(), nullable=False),
        sa.Column("acquisition_cost_minor", sa.BigInteger(), nullable=False),
        sa.Column("operational_cost_minor", sa.BigInteger(), nullable=False),
        sa.Column("capital_carry_cost_minor", sa.BigInteger(), nullable=False),
        sa.Column("partial_fill_reserve_minor", sa.BigInteger(), nullable=False),
        sa.Column("all_in_cost_minor", sa.BigInteger(), nullable=False),
        sa.Column("expected_output_value_minor", sa.BigInteger(), nullable=False),
        sa.Column("ev_net_minor", sa.BigInteger(), nullable=False),
        sa.Column("lower_bound_ev_minor", sa.BigInteger(), nullable=False),
        sa.Column("worst_case_pnl_minor", sa.BigInteger(), nullable=False),
        sa.Column("best_case_pnl_minor", sa.BigInteger(), nullable=False),
        sa.Column("profit_per_capital_day_minor", sa.BigInteger(), nullable=False),
        sa.Column("expected_orphan_loss_minor", sa.BigInteger(), nullable=False),
        sa.Column("roi_net", sa.String(length=64), nullable=False),
        sa.Column("probability_of_profit", sa.String(length=64), nullable=False),
        sa.Column("expected_capital_days", sa.String(length=32), nullable=False),
        sa.Column("bundle_completion_probability", sa.String(length=32), nullable=False),
        sa.Column("unvaluable_probability_mass", sa.String(length=64), nullable=False),
        sa.Column("max_quote_age_seconds", sa.String(length=32), nullable=False),
        sa.Column("output_confidence_floor", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.candidate_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("candidate_evaluations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_evaluations_candidate_id"), ["candidate_id"], unique=False
        )

    op.create_table(
        "candidate_rejections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("candidate_id", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reasons", sa.String(length=1024), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.candidate_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("candidate_rejections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_rejections_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_candidate_rejections_stage"), ["stage"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("candidate_rejections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_rejections_stage"))
        batch_op.drop_index(batch_op.f("ix_candidate_rejections_candidate_id"))

    op.drop_table("candidate_rejections")
    with op.batch_alter_table("candidate_evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_evaluations_candidate_id"))

    op.drop_table("candidate_evaluations")
    op.drop_table("candidates")
    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scans_scanned_at"))

    op.drop_table("scans")
    with op.batch_alter_table("reservations", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_active_reservation_per_listing",
            sqlite_where=sa.text("is_active IS 1"),
            postgresql_where=sa.text("is_active IS 1"),
        )
        batch_op.drop_index(batch_op.f("ix_reservations_candidate_id"))

    op.drop_table("reservations")
    op.drop_table("realized_contract_results")
    op.drop_table("raw_payloads")
    op.drop_table("metadata_snapshots")
    with op.batch_alter_table("listings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_listings_venue"))
        batch_op.drop_index(batch_op.f("ix_listings_skin_id"))
        batch_op.drop_index(batch_op.f("ix_listings_collection_id"))
        batch_op.drop_index(batch_op.f("ix_listings_asset_id"))
        batch_op.drop_index("ix_listing_collection_rarity")

    op.drop_table("listings")
    with op.batch_alter_table("ledger_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ledger_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_ledger_events_item_id"))
        batch_op.drop_index(batch_op.f("ix_ledger_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_ledger_events_contract_id"))

    op.drop_table("ledger_events")
    with op.batch_alter_table("inventory_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_items_state"))
        batch_op.drop_index(batch_op.f("ix_inventory_items_skin_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_items_contract_id"))

    op.drop_table("inventory_items")
    # ### end Alembic commands ###
