"""Acceptance gate G15: record what actually ran, with real exit codes.

Runs each verification command, captures its exit status and the numbers it printed,
and writes ``artifacts/evidence/verification.json``.

Written as a tool rather than a hand-maintained file so the evidence cannot drift
from reality. A status document transcribed by hand is a claim; one generated by
running the commands is a measurement.

Usage::

    uv run python tools/write_verification.py
"""

from __future__ import annotations

import json
import platform
import re
import shutil
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EVIDENCE = REPO_ROOT / "artifacts" / "evidence" / "verification.json"

COMMANDS: tuple[tuple[str, list[str]], ...] = (
    ("format_check", ["uv", "run", "ruff", "format", "--check", "."]),
    ("lint", ["uv", "run", "ruff", "check", "."]),
    ("typecheck", ["uv", "run", "mypy"]),
    # No extra -q: pyproject's addopts already carries one, and -qq suppresses the
    # summary line this tool parses the test count out of.
    ("tests", ["uv", "run", "pytest", "--cov", "--cov-report=json"]),
    ("coverage_floors", ["uv", "run", "python", "tools/check_coverage.py"]),
    ("no_placeholders", ["uv", "run", "python", "tools/check_no_placeholders.py"]),
    ("migrate_up", ["uv", "run", "alembic", "upgrade", "head"]),
    ("migrate_down", ["uv", "run", "alembic", "downgrade", "base"]),
    ("demo", ["uv", "run", "tradeup", "demo", "--quiet"]),
)


def _resolve(command: list[str]) -> list[str]:
    """Translate ``uv run X …`` for environments where ``uv`` is not on PATH.

    The gate still runs the real tool from this interpreter's environment; only the
    launcher differs, and the recorded command string is the one actually executed.
    """
    if shutil.which("uv") is not None or command[:2] != ["uv", "run"]:
        return command
    head, *rest = command[2:]
    if head == "python":
        return [sys.executable, *rest]
    scripts_dir = str(Path(sys.executable).parent)
    resolved = shutil.which(head, path=scripts_dir)
    if resolved is not None:
        return [resolved, *rest]
    return [sys.executable, "-m", head, *rest]


def _run(command: list[str]) -> tuple[int, str]:
    result = subprocess.run(command, cwd=REPO_ROOT, capture_output=True, text=True, check=False)
    return result.returncode, (result.stdout or "") + (result.stderr or "")


def _search(pattern: str, text: str) -> str | None:
    match = re.search(pattern, text)
    return match.group(1) if match else None


def main() -> int:
    results: dict[str, dict[str, object]] = {}
    outputs: dict[str, str] = {}

    for name, command in COMMANDS:
        actual = _resolve(command)
        code, output = _run(actual)
        outputs[name] = output
        results[name] = {
            "command": " ".join(actual),
            "exit_code": code,
            "passed": code == 0,
        }
        status = "ok" if code == 0 else "FAILED"
        print(f"{name:<18} exit={code:<3} {status}")

    test_output = outputs.get("tests", "")
    test_count = _search(r"(\d+) passed", test_output)
    coverage_output = outputs.get("coverage_floors", "")
    overall = _search(r"overall\s+(\d+\.\d+)%", coverage_output)

    per_module: dict[str, str] = {}
    for line in coverage_output.splitlines():
        match = re.match(r"^(src/\S+\.py)\s+(\d+\.\d+)%", line)
        if match:
            per_module[match.group(1)] = match.group(2) + "%"

    demo_output = outputs.get("demo", "")
    approved = _search(r"(\d+) candidate\(s\) cleared all gates", demo_output)
    rejected = _search(r"cleared all gates, (\d+) rejected", demo_output)
    rejections = _search(r"rejections_by_reason\s+(\S+)", demo_output)

    coverage_json = REPO_ROOT / "coverage.json"
    manifest_files = sorted((REPO_ROOT / "data" / "metadata").glob("*.manifest.json"))
    metadata_manifest: dict[str, object] = {}
    if manifest_files:
        metadata_manifest = json.loads(manifest_files[0].read_text(encoding="utf-8"))

    payload = {
        "generated_at": datetime.now(UTC).isoformat(),
        "generated_by": "tools/write_verification.py",
        "environment": {
            "python": sys.version.split()[0],
            "platform": platform.platform(),
        },
        "commands": results,
        "all_gates_passed": all(bool(r["passed"]) for r in results.values()),
        "tests": {
            "count": int(test_count) if test_count else None,
            "network_required": False,
            "hypothesis_mode": "derandomize",
        },
        "coverage": {
            "overall_percent": float(overall) if overall else None,
            "critical_module_floor_percent": 90.0,
            "overall_floor_percent": 80.0,
            "per_critical_module": per_module,
            "report": coverage_json.name if coverage_json.exists() else None,
        },
        "metadata": {
            "upstream_repo": metadata_manifest.get("upstream_repo"),
            "upstream_commit": metadata_manifest.get("upstream_commit"),
            "upstream_sha256": metadata_manifest.get("upstream_sha256"),
            "projection_sha256": metadata_manifest.get("projection_sha256"),
            "projection_entry_count": metadata_manifest.get("projection_entry_count"),
        },
        "offline_demo": {
            "approved_candidates": int(approved) if approved else None,
            "rejected_candidates": int(rejected) if rejected else None,
            "rejection_census": rejections,
            "data_nature": "SYNTHETIC listings and prices over REAL pinned metadata",
            "artifacts_dir": "artifacts/evidence/",
        },
        "live_checks": {
            "performed": False,
            "reason": (
                "No marketplace credentials are configured in this environment. "
                "`make live-smoke` skips cleanly; no live read has been performed "
                "against CSFloat, DMarket or SkinSnipe."
            ),
        },
        "economic_evidence": {
            "settled_fee_net_profit_usd": "0.00",
            "ledger_events": 0,
            "orders_placed": 0,
            "fills": 0,
            "trade_ups_completed": 0,
            "sales": 0,
            "settlements": 0,
            "real_market_qualified_opportunities": 0,
            "simulated_opportunities": int(approved) if approved else 0,
            "note": (
                "Zero across the board. The system has never contacted a live "
                "marketplace with credentials, placed an order, performed a "
                "trade-up, or settled proceeds. The simulated opportunity count "
                "comes from synthetic prices and is not market evidence."
            ),
        },
    }

    EVIDENCE.parent.mkdir(parents=True, exist_ok=True)
    EVIDENCE.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"\nwrote {EVIDENCE.relative_to(REPO_ROOT).as_posix()}")
    return 0 if payload["all_gates_passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
